name: pull_request
on: pull_request
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DigitalOcean
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com/jackhughes
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}